import {Prisma} from "@prisma/client";
export const select_complete_record:Prisma.machine_dataSelect={
    id:true,
    name:true,
    gameType:true,
    gameZone:true,
    modelNumber:true,
    serialNumber:true,
    dateOfMfg:true,
    dateEnter:true,
    dateExit:true,
    occupied:true,
    opState:true,
    playerCount:true,
    cabinetKey:true,
    serviceKey:true,
    attachments:true,
    timestamp:true,
    contacts:{
        select:{
            id:true,
            name:true,
            type:true,

        }
    },
    issues:true,
    todo:true,
    comments:{
        select:{
            content:true
        }
    },
    timestampObject: {
        select:{
            createdAt:true,
            user_createdBy:{
                select:{
                    id:true,
                    username:true,
                    displayName:true
                }
            },
            lastAccess:true,
            user_lastAccessBy:{
                select:{
                    id:true,
                        username:true,
                        displayName:true
                }
            },
            modifiedAt:true,
            user_modifiedBy:{
                select:{
                    id:true,
                        username:true,
                        displayName:true
                }
            },
        }
    }
}