openapi: 3.1.0
info:
  title: Arcateched API
  version: 0.1.1
  description: The definition of the Arcateched API
paths:
  /api/get/id/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/id"
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/gameNameResponse"
          description: "A list of game names and machine IDs"
components:
  schemas:
    id:
      properties:
        type: string
        format: UUID
        description: A machine ID number
    gameName:
      properties:
        type: string
        description: The title of the fame
        minimum: 4
        maximum: 64
    gameNameResponse:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/id"
        gameName:
          $ref: "#/components/schemas/gameName"
    keys_machine_data_cabinetKeyTokeys:
      type: object
      description: A cabinetKey object
      properties:
        id:
          $ref: "#/components/schemas/id"
        keyID:
          type: string
          description: A string containing an identification of the key
        tagLabel:
          type: string
          description: A string containing the label of the key
        keyForm:
          type: number
          description: An object containing the type of key
        keyType:
          type: number
          description: An object containing the type of key
        idMarks:
          type: array
          description: A list of strings containing identifying marks on the key
    keys_machine_data_serviceKeyTokeys:
      $ref: "#/components/schemas/keys_machine_data_cabinetKeyTokeys"



    gameById:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/id"
        gameName:
          $ref: "#/components/schemas/gameName"
        modelNumber:
          type: string
          description: The model number of the machine
          maximum: 32
        serialNumber:
          type: string
          description: The serial number of the machine
          maximum: 32
        dateOfMfg:
          type: number
          description: The UNIX timestamp of the machine's date of manufacture
        dateEnter:
          type: number
          description: The UNIX timestamp of the machine's entrance into service
        dateExit:
          type: number
          description: The UNIX timestamp of the machine's retirement from service
        cabinetKey:
          type: string
          format: UUID
          description: The ID of the cabinet key object
        serviceKey:
          type: string
          format: UUID
          description: The ID of the service key object
        playerCount:
          type: number
          description: The number of players a game will support simultaneously
        gameType:
          type: array
          description: An array of tags that describe game operation
          enum:
            - Redemption
            - Video
            - Skill
            - Pusher
            - Merch
            - Crane
        gameZone:
          type: string
          format: UUID
          description: An identifier linked to an object that describes the physical space a machine occupies
        occupied:
          type: number
          description: A number that indicated how much floor space a machine occupies
        timestamp:
          type: string
          format: UUID
          description: An identifier linked to an object that holds timing metadata
        mfgUUID:
          type: string
          format: UUID
          description:  An identifier linked to an object in the contacts table, used to identify the manufacturer of the machine
        attachments:
          type: array
          description: An array of linked attachment objects in the attachments table
        comments:
          type: array
          description: An array of linked comment objects in the comments table
        issues:
          type: array
          description: An array of linked issue tracker objects that are associated with the machine

